name: digihero
description: A complex gamified Flutter game for digital literacy education using Flutter Causal Games toolkit
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Flutter Causal Games toolkit
  games_services: ^4.0.0
  flame: ^1.15.0
  flame_forge2d: ^0.16.0
  flame_audio: ^2.0.0
  flame_svg: ^1.8.0
  
  # UI and animations
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.2.0
  rive: ^0.12.4
  lottie: ^2.7.0
  
  # State management and utilities
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  
  # Audio and media
  audioplayers: ^5.2.1
  
  # Networking and data
  http: ^1.1.0
  dio: ^5.3.4
  
  # Local storage
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/characters/
    - assets/images/sprites/
    - assets/images/backgrounds/
    - assets/images/ui/
    - assets/audio/
    - assets/audio/music/
    - assets/audio/sfx/
    - assets/data/
    - assets/animations/
    
  fonts:
    - family: GameFont
      fonts:
        - asset: assets/fonts/game_font_regular.ttf
        - asset: assets/fonts/game_font_bold.ttf
          weight: 700